const fetch = require('node-fetch');

// Helper to send message via CallMeBot
const sendWhatsApp = async (phone, text, apikey) => {
    if (!phone || !apikey) {
        console.log(`WhatsApp NOT sent: Missing phone or apikey for ${phone}`);
        return { success: false, error: 'Missing phone or apikey' };
    }

    // Clean phone number (remove +, spaces, dashes)
    const cleanPhone = phone.replace(/[\+\s\-]/g, '');

    const url = `https://api.callmebot.com/whatsapp.php?phone=${cleanPhone}&text=${encodeURIComponent(text)}&apikey=${apikey}`;

    try {
        console.log(`Attempting to send WhatsApp to: ${cleanPhone}`);
        const response = await fetch(url);
        const data = await response.text();

        if (response.ok) {
            console.log('WhatsApp sent successfully');
            return { success: true };
        } else {
            console.error('WhatsApp send failed:', data);
            return { success: false, error: data };
        }
    } catch (error) {
        console.error('WhatsApp send error:', error.message);
        return { success: false, error: error.message };
    }
};

const sendWelcomeWhatsApp = async (phone, apikey, name, farmName) => {
    const text = `🐄 *Welcome to FarmXpert!*\n\nCongratulations, ${name}!\nYour farm *"${farmName}"* has been successfully registered.\n\nEnjoy tracking your cattle, managing feed, and logging vaccinations!`;
    return sendWhatsApp(phone, text, apikey);
};

const sendAnimalOwnerWelcomeWhatsApp = async (phone, apikey, name, animalTag, farmName) => {
    const text = `🐄 *FarmXpert Registration*\n\nHello ${name}!\nGreat news! Your animal *${animalTag}* has been registered at *${farmName}*.\n\nYou will receive updates on its health, weight, and payments.`;
    return sendWhatsApp(phone, text, apikey);
};

const sendLowStockAlertWhatsApp = async (phone, apikey, ownerName, farmName, lowStockItems) => {
    let itemsText = lowStockItems.map(item => `- ${item.name}: ${item.quantityKg}kg (Min: ${item.lowStockThreshold}kg)`).join('\n');
    const text = `⚠️ *URGENT: Low Feed Stock Alert*\n\nFarm: *${farmName}*\nDear ${ownerName},\n\nThe following items are below minimum threshold:\n${itemsText}\n\nPlease restock immediately!`;
    return sendWhatsApp(phone, text, apikey);
};

const sendAnimalReportWhatsApp = async (phone, apikey, name, reportData) => {
    const text = `📈 *Animal Report: ${reportData.tagNumber}*\n\nHello ${name} 👋\nHere is the latest status for your animal:\n\n⚖️ *Weight:* ${reportData.currentWeight} kg\n🧬 *Breed:* ${reportData.breed}\n📌 *Status:* ${reportData.status}\n🩺 *Vaccination:* ${reportData.vaccinationStatus ? '✅ Up to Date' : '❌ Pending'}\n💰 *Monthly Charges:* Rs. ${reportData.monthlyCharges.toLocaleString()}\n\nGenerated by FarmXpert 🐄`;
    return sendWhatsApp(phone, text, apikey);
};

module.exports = {
    sendWhatsApp,
    sendWelcomeWhatsApp,
    sendAnimalOwnerWelcomeWhatsApp,
    sendLowStockAlertWhatsApp,
    sendAnimalReportWhatsApp
};
